Use SDK from separate directory
Otherwise GAE will ignore it's own modules because they are in hidden
(starting with dot) directory:

$ ./manage.py runserver
WARNING:root:No ssl package found. urlfetch will not be able to validate SSL certificates.
WARNING:root:Could not read datastore data from /home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.gaedata/datastore
WARNING:root:Could not initialize images API; you are likely missing the Python "PIL" module. ImportError: No module named _imaging
INFO:google.appengine.tools.appengine_rpc:Server: appengine.google.com
INFO:root:Checking for updates to the SDK.
INFO:root:The SDK is up to date.
WARNING:root:Could not read datastore data from /home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.gaedata/datastore
INFO:root:Connecting to SQLite database '' with file '/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.gaedata/rdbms'
WARNING:root:Could not initialize images API; you are likely missing the Python "PIL" module. ImportError: No module named _imaging
INFO:root:Running application unknownwords on port 8000: http://localhost:8000
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/fancy_urllib/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/yaml/lib/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/ipaddr/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/graphy/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/antlr3/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/simplejson/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/lib/webob/django"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/django/.svn/entries"
WARNING:root:Blocking access to skipped file "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/dist/tempfile.py"
DEBUG:root:Access to module file denied: /home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/dist/tempfile.py
ERROR:root:Exception encountered handling request
Traceback (most recent call last):
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 4053, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 3977, in _Dispatch
    base_env_dict=env_dict)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 588, in Dispatch
    base_env_dict=base_env_dict)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 3050, in Dispatch
    self._module_dict)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2954, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2834, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/djangoappengine/main/main.py", line 28, in <module>
    from django.core.handlers.wsgi import WSGIHandler
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/django/core/handlers/wsgi.py", line 10, in <module>
    from django import http
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/django/http/__init__.py", line 22, in <module>
    from cgi import parse_qsl
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/usr/lib/python2.5/cgi.py", line 41, in <module>
    import mimetools
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2450, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2339, in FindAndLoadModule
    description)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2282, in LoadModuleRestricted
    description)
  File "/usr/lib/python2.5/mimetools.py", line 6, in <module>
    import tempfile
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2009, in find_module
    search_path)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 1505, in Decorate
    return func(self, *args, **kwargs)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2333, in FindAndLoadModule
    module = self.ImportStubModule(submodule_fullname)
  File "/home/bob/public/semester10/git/Internet_technologies/unknown_words/server/.google_appengine/google/appengine/tools/dev_appserver.py", line 2051, in ImportStubModule
    return getattr(module, name)
AttributeError: 'module' object has no attribute 'tempfile'
INFO:root:"GET / HTTP/1.1" 500 -