Workaround for GAE error message
Checking if deployment succeeded.
Will check again in 4 seconds.
Completed update of app: learnsubtitles, version: 1
Uploading index definitions.
Uploading cron entries.
Running syncdb.
Error: One or more models did not validate:
learnsubtitles.dictionary: "test": CharFields require a "max_length"
attribute that is a positive integer.